### ISSUE TITLE
Roadmap for 0.3.0

### ISSUE THREAD

**Issue by liuq19** [cloudwego/sonic-rs#39]
In sonic-rs 0.3.0, the `Document` will be refactored to make it easy to use as `serde_json::Value`, and still with high-performance.

Break Changing Checklist:

## Basic APIs
- [x] the untyped `Value`  APIs
- [x] the `Array` APIs
- [x] the `Object` APIs
- [x] add `json!` macros

## Serde traits
- [x] impl serde trait for `Value`
- [x]  impl serde trait for `Array`
- [x]  impl serde trait for `Object`

## Iterator
- [x]  impl iterator trait for `Value`
- [x]  impl iterator trait for `Array`
- [x]  impl iterator trait for `Object`

## MISC
- [x] impl PartailEq
- [x] impl From
- [x] impl Index
- [x] impl Extend
