### ISSUE TITLE
Sonic-rs 0.4 RoadMap

### ISSUE THREAD

**Issue by liuq19** [cloudwego/sonic-rs#66]
We plan to release sonic-rs 0.4 before ~~April~~ Jun.

### Break Change:

- [x]  Optimize `pointer!` in #83 
- [x]  Refactor `sonic_rs::Value`, disable assignment `=` and replace it with `set` API
- [x] Split the crate, only provide all `unsafe` API in a new crate

### Enhanced

- [ ] ~~FastStr/Bytes zero-copy~~ ( I don't know to how to do it)
- [ ] Runtime detection
- [x] #54 
- [x] #43 
- [x] implement `get_by_schema()`

### Bug Fix
- [x] #75 
- [ ] Fix miri tests #61 
...

**Comment by nyabinary** [comment]
any update?

**Comment by liuq19** [comment]
I am tooo busy now, and I will update it in May. Emm...

If you have a details problem, welcome to open a new issue ~
